server:
    port: 8443
    ssl:
        enabled: true
        key-alias: spring
        key-store: src/main/resources/saml/keystore.jks
        key-store-password: 123456

security:
    saml2:
        metadata-url: https://dev-663276.oktapreview.com/app/exke81fbb4UqHKxt60h7/sso/saml/metadata
